echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "Hello, How are you?"
echo "This is git practice"
echo "We are doing practicle of branching"
echo "Practicing from linux machine"
echo "Practicing Merge Conflict"
echo "This is branch_1 Edit"
echo "Good Evening"
echo "This is branch_2 Edit"